halloweenDialogs:
  jezibaba: "Zdravím tě, poutníku. Měla bych pro tebe nabídku. Přinesl-li bys mi 2x Kopřivu a 1x Tuřín do mého lektvaru, štědře bych se ti odměnila."
  prekupnik1: "Zdravíčko, dostal jsem zakázku od mého dlouhodobého zákazníka chovatele a nerad bych ho zklamal, donesl bys mi prosím 4x Černou vdovu a 4x Vrka? Odměna tě nemine!"
  prekupnik2: "Ouu..  pochop, že jsem ve velice složité životní situaci, a potřebuji peníze... Donesl bys mi prosím ještě 4x Netopýra a 2x Krysu? Měl by o ně zájem jeden bohatý kupec ze severu, který mi nabízí kupu peněz."
  pruzkumnik: "Hoj, potřeboval bych po tobě 2x Zářivé bobule na další cesty. Mimochodem, v lesích daleko odsud jsem našel podivný předmět, pomůžeš-li mi, daruji ti ho."
  lupic1: "Čau, vypadáš jako hodný chlapík. Mohl bys mi, prosím, donést 2x Prohnilou dýni?"
  lupic2: "Neměl bys ještě Kořen mandragory, prosím?"
  lupic3: "Ještě Vejce Jormungandra a bude to vše..."
  lupic4: "Jen pro pořádek, neřekl jsem nic o tom, že ti něco dám. :)"